name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Or your default branch, e.g., master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme
        pip install -e .

    - name: Build documentation
      run: |
        cd docs  # Replace 'docs' with your documentation directory, if different
        sphinx-apidoc -f -o . ../DMDana
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html  # Update path according to your build output directory
